README.md

Adding initial technologies for project development

Add technologies and links to README

---

client/src/components/Forms/Base/BaseSelect.jsx
client/src/components/Forms/Base/index.js
client/stories/index.stories.js

Created BaseSelect.jsx Component and added it to storybook.'

Add Generic Dropdown Component #51

---

client/src/components/Forms/Base/BaseDateTimePicker.jsx
client/src/components/Forms/Base/index.js
client/src/components/common/DateTimePicker.jsx
client/src/components/common/index.js
client/stories/index.stories.js

Adding date/time pickers to storybook.

add date and time pickers to storybook

---

.gitignore
server/k8s/flask-ui/app/Dockerfile
server/k8s/flask-ui/app/src/app.py
server/k8s/flask-ui/app/src/client/package-lock.json
server/k8s/flask-ui/app/src/client/package.json
server/k8s/flask-ui/app/src/client/src/index.html
server/k8s/flask-ui/app/src/client/src/index.tsx
server/k8s/flask-ui/app/src/client/tsconfig.json
server/k8s/flask-ui/app/src/client/webpack.config.js
server/k8s/flask-ui/app/src/startup.sh
server/k8s/flask-ui/app/src/templates/index.html
server/k8s/flask-ui/deployment.yaml
server/k8s/flask-ui/service.yaml
server/k8s/postgres/app/Dockerfile
server/k8s/postgres/app/initsharedhousingdb.sql
server/k8s/postgres/deployment.yaml
server/k8s/postgres/service.yaml

Self-contained "k8s" folder is a proof-of-concept integrating the full tech stack selected for Shared Housing project. Dockerized Flask serving React SPA backed by PostgreSQL in separate container. Kubernetes deployments and services tested on minikube.

basic end-to-end integration

---

docs/README.md

Adding gitbook documentation link to readme.

Issue#72 gitbook

---

docs/backend_readme.md

This is the initial check in for the backend guide. We need to get this going as new members are being onboarded.

Documentation: initial check in for backend guide #133

---

client/src/App.jsx
client/src/components/PrototypeForm/PrototypeForm.jsx
client/src/routes/index.js

Issue # 144 Created a PrototypeForm component and route.

Prototype Form

---

client/src/components/Dashboard/Base/BaseAvatar.jsx
client/src/components/Dashboard/Base/index.js
client/stories/Dashboard.stories.js

Created BaseAvatar under Dashboard components file structure, and added to storybook under new Dashboard tab.

Add BaseAvatar under Dashboard components, add to storybook

---

client/.storybook/config.ts
client/.storybook/webpack.config.js
client/package-lock.json
client/package.json
client/tsconfig.json

Part of https://github.com/hackforla/shared-housing/issues/68

Enable use of TypeScript in project

---

client/src/pages/Error404.jsx
client/stories/Pages.stories.js

Also add it to Storybook.
Closes #70
---
Preview img:

Add Error404 component

---

server/k8s/flask-ui/app/api/config.py
server/k8s/flask-ui/app/api/main.py
server/k8s/flask-ui/app/api/models/models.py
server/k8s/flask-ui/app/api/routes/candidates_response.py
server/k8s/flask-ui/app/api/run.py
server/k8s/flask-ui/app/api/utils/migrate.py
server/k8s/flask-ui/app/api/utils/responses.py

I added descriptions to all the files I created in the api folder.

Doc: Include file descriptions

---

server/k8s/flask-ui/app/api/utils_ivan/eligibility.py

Made the initial eligibility filter.

resolves hackforla/shared-housing#160

---

client/src/components/Dashboard/Base/BaseChip.jsx
client/src/components/Dashboard/Base/index.js
client/stories/Dashboard.stories.js

Created a base chip component for dashboard.
* Added component to storybook
* accepts props for labeling and styling

Created dashboard chip component #91

---

docs/getting-started.md
docs/overview.md

Fixed some minor grammar errors and created a link for the repo to fork.  First PR in a while, let me know if I need to do anything different.

issue #118, minor grammar fixes, added link to repo

---

.gitignore
client/package-lock.json
client/package.json
client/webpack-dev.config.js

* Installed webpack-dev-server
* Updated package.json with dev server script "npm run dev"
* Updated webpack-dev.config.js to use files properly and show better error messages

Added frontend development server

---

client/src/components/MainNav/MainNav.jsx
client/src/components/PrototypeForm/PrototypeForm.jsx

Styling is still very rough. Closes #166

Refactor PrototypeForm component to use Material-UI

---

client/package-lock.json

low level reg x vulnerability fix

braces updated to 2.3.1 or greater #196

---

client/src/components/common/NewsFeed.jsx

* Add css rules to avatar image

Fix NewsFeex.jsx avatar image scale #217

---

client/src/components/MainNav/MainNav.jsx

* Refactored navbar buttons rendering
* Added Menu and MenuItems for hamburger button
* Only show Hamburger when screen size is small
* Resolves #213

Added navbar hamburger functionality

---

client/src/components/common/NewsFeed.jsx
client/src/hooks/useAPI.js

* Added error message in NewsFeed Component
* Added loader for NewsFeed Component
* Added better error handling in useAPI hook
* Resolves #227

Fix NewsFeed Component error handling

---

server/api/main.py
server/api/matcher/constraint_filter.py
server/api/models/sqlalchemy/models.py
server/api/resources/sh.local.postman_environment.json
server/api/resources/sh.postman_collection.json
server/api/routes/sqlalchemy/candidates_response.py
server/api/routes/sqlalchemy/form.py
server/api/routes/sqlalchemy/location_resources.py
server/api/routes/sqlalchemy/location_response.py
server/api/routes/sqlalchemy/question.py
server/api/utils_ivan/eligibility.py

This PR is the rough outline for applying constraints (filters) to location/candidate pairings based on the questions answered. 
The gist of the logic is a single question (represented by a questionId) has two questions, a candidate question and a location question. These two questions are tied together. The relationship they share is either an inverse or direct relationship. The question is also a constraint or not a constraint.
Given the above foundation, a candidate response has a questionId and a candidateId along with a responseValue. A location response has a questionId and a locationId along with a responseValue. 
Eligibility will check a single location's responses and compare that with a single candidate's responses. 
ConstraintFilter will check a single location against all …

Expand Routes to Handle Candidate Location Matching

---

client/src/components/Demo/UnitForm.js
client/stories/Forms.stories.js

* Add the "unit form" for issue #234
* Added to storybook
* Added `Q: Is this unit handicap accessible`
* Still needs to be added to site

Add Unit Form for demo

---

docs/introductions/shared-housing-project-overview-2019-06/index.html

Add document "Shared Housing Project Overview 2019-06". 
This commit is a simplified HTML translation of [Shared Housing Project Overview Jun-2019.pptx](https://drive.google.com/file/d/1ZyUEjJqntZQ5SeTuT9m4hoDXytujzcmd/view). 
The purpose is to get the text into the repo, so it's available to the team developers inside the repo.

Add doc of Shared Housing Project Overview 2019-06

---

docs/introductions/shared-housing-presentation-2019-09-17/index.html
docs/introductions/shared-housing-project-overview-2019-06/index.html

Add the introductory presentation. This commit is a quick-and-dirty HTML translation of the original Google deck. The purpose of this commit is to give the team the content ASAP to be ready for consideration on an upcoming landing page.
The CSS styles are just made up. Feel free to add/change/delete as you like.
This pull request also includes a cherry pick from a related branch that also has a pull request in progress.

Add doc: Shared Housing presentation 2019-09-17

---

server/api/main.py
server/api/routes/sqlalchemy/location_candidate.py
server/api/routes/sqlalchemy/location_response.py

add location candidate route which will allow frontend to grab all eligible candidates for a location
GET <url>/api/v1/locationcandidates/<location_id>
Response looks like:
[
{
"candidateId": 1,
"name": "tyler"
},
{
"candidateId": 2,
"name": "josh"
},
{
"candidateId": 3,
"name": "karlan"
}
]

add candidate location route to grab all eligible candidates for a location

---

docs/tutorials/user-story-examples-for-match-score.md

Add user story examples of a kind of match-score tool. These user stories are public, and also shareable, and also intended for demos, tutorials, trainings, and discussions.
The purpose of this commit is to help the team because a teammate asked me "What do you think is a user story?" and also asked for examples.

Add user story examples

---

client/src/components/Dashboard/Unit/UnitCard.tsx
client/src/components/Dashboard/Unit/index.js
client/stories/Dashboard.stories.js

created a UnitCard react component for use in Unit dashboard. Takes in a variety of props that are then formatted in the card wireframe outlined.
* Added to storybook
* Used material-ui
* Takes in props
* Typescript
* resolves #262

Add UnitCard React Component

---

client/.eslintrc
client/package-lock.json
client/package.json
client/src/components/Dashboard/Unit/UnitCard.tsx
client/src/components/Dashboard/Unit/UnitListItem.tsx
client/src/components/Dashboard/Unit/index.js
client/stories/Dashboard.stories.js
client/webpack-dev.config.js
client/webpack-prod.config.js

Add UnitListItem React component for use in dashboard. Written in TypeScript and takes in required props.
* Takes in required props
* Use material-ui
* Add to storbook
* resolves #263
* Used figma wireframe as reference
* Update eslint config for typescript import

Unit list item

---

projects/landing/index.html

Add the simplest-possible landing page, which is merely a first step placeholder, with a the "Homeless" text image, and the introductory presentation text. 
We will replace the image and text as soon as soon as we can iterate.

Add landing page first step

---

docs/backend_readme.md

Fixing the heading markdown formatting.

Minor Formatting Fixes

---

client/src/components/Dashboard/Tenant/TenantList.jsx
client/stories/Dashboard.stories.js

Create TenantList component.

---

client/src/components/Dashboard/Tenant/TenantList.jsx
client/src/components/Dashboard/Tenant/TenantListItem.jsx
client/stories/Dashboard.stories.js

Create TenantListItem component
